export const SET_USERNAME = "SET_USERNAME";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_CATEGORY_ITEM = "SET_CATEGORY_ITEM";
export const SET_STAGED = "SET_STAGED";
export const SET_LOADING = "SET_LOADING";
export const GET_STAGED_ITEMS = "GET_STAGED_ITEMS";

// export const SET_SESSION_STATE = "SET_SESSION_STATE";
